### PR TITLE
25 get contacts

### PR DESCRIPTION
**Pull request by peacebonez**
adds GET method to routes/users.js to get all contacts

### CODE REVIEW

**Review by ThinkTink — APPROVED** [review]
Two thoughts here:
1) no contacts should be 204 + empty array like with the invitations
2) What all is returned in user.contacts? Is there any information that we don't want to send to the front end (like, does it fetch the full user, password included, for all contacts?) If so, we might need to do something like this - https://medium.com/@contactsunny/hide-properties-of-mongoose-objects-in-node-js-json-responses-a5437a5dbec2

**Comment by peacebonez** [comment]
How's this for de-selecting user password when retrieving the user:

const user = await User.findById(userId).select("-password");

Looks like I'll need to apply this to all the user contacts as well when retrieving

**Comment by peacebonez** [comment]
added this to the User model file

UserSchema.methods.toJSON = function () {
  let obj = this.toObject();
  obj.contacts.forEach((contact) => {
    delete contact.password;
  });
};

How's this look?

**Comment by ThinkTink** [comment]
> added this to the User model file
> 
> UserSchema.methods.toJSON = function () {
> let obj = this.toObject();
> obj.contacts.forEach((contact) => {
> delete contact.password;
> });
> };
> 
> How's this look?

I was thinking something more like:
```
UserSchema.methods.toJSON = function () {
  const user = this.toObject();
  delete user.password;
  return user;
};
...
const user = await User.findById(userId);
const contacts = user.contacts.map( contact =>
  contact.toJSON()
)
res.json(.contacts);
```

We could also adapt what you have by changing the function name to getContacts() and returning obg.contacts, as long as you verify that it doesn't permanently delete those contacts' passwords...

**Pull request merged**
